// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/alnvdl/gomockcmp/external (interfaces: ServiceClient)

// Package mock is a generated GoMock package.
package mock

import (
	reflect "reflect"

	external "github.com/alnvdl/gomockcmp/external"
	gomock "github.com/golang/mock/gomock"
)

// MockServiceClient is a mock of ServiceClient interface.
type MockServiceClient struct {
	ctrl     *gomock.Controller
	recorder *MockServiceClientMockRecorder
}

// MockServiceClientMockRecorder is the mock recorder for MockServiceClient.
type MockServiceClientMockRecorder struct {
	mock *MockServiceClient
}

// NewMockServiceClient creates a new mock instance.
func NewMockServiceClient(ctrl *gomock.Controller) *MockServiceClient {
	mock := &MockServiceClient{ctrl: ctrl}
	mock.recorder = &MockServiceClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockServiceClient) EXPECT() *MockServiceClientMockRecorder {
	return m.recorder
}

// DoSomething mocks base method.
func (m *MockServiceClient) DoSomething(arg0 string) (external.ServiceClientObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoSomething", arg0)
	ret0, _ := ret[0].(external.ServiceClientObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoSomething indicates an expected call of DoSomething.
func (mr *MockServiceClientMockRecorder) DoSomething(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSomething", reflect.TypeOf((*MockServiceClient)(nil).DoSomething), arg0)
}

// DoSomethingSlightlyDifferent mocks base method.
func (m *MockServiceClient) DoSomethingSlightlyDifferent(arg0 string) (external.ServiceClientObject, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DoSomethingSlightlyDifferent", arg0)
	ret0, _ := ret[0].(external.ServiceClientObject)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DoSomethingSlightlyDifferent indicates an expected call of DoSomethingSlightlyDifferent.
func (mr *MockServiceClientMockRecorder) DoSomethingSlightlyDifferent(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DoSomethingSlightlyDifferent", reflect.TypeOf((*MockServiceClient)(nil).DoSomethingSlightlyDifferent), arg0)
}
